version: "3.4"

services:

  mariadb:
    image: mariadb:10.3.4
    networks:
      - dbnet
    ports:
      - "3306"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: "HUCtTVGd2qPnAHYTZc9zTKgJ"
      MYSQL_DB: "web"
      MYSQL_USER: "webuser"
      MYSQL_PASSWORD: "HUCtTVGd2qPnAHYTZc9zTKgJ"
      volumes:
        - mariadb:/var/lib/mysql
      restart: on-failure
      
pma:
      
web:
  image: httpd:1.0
  networks:
    - dbnet
  port::
    - "80:80
  stop_grace_period: 10s
  volumes:
    - /users/jdavid/IntroDocker/lamp:var/www/html
      
networks:
  dbnet:
    external: true
      
volumes:
  mariadb:
    external: true
  sessions:
    external: true