# -*- mode: ruby -*-

# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
# Staat standaard op virtualbox maar kan op hyperv gezet worden
# ALS JE HYPERV GEBRUIKT MOET JE config.vm.network IN COMMENTAAR ZETTEN
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
    # IP Adres toevoegen aan virtuele machine
    # IN COMMENTAAR ZETTEN ALS JE HYPERV GEBRUIKT, NOG NIET ONDERSTEUND DOOR VAGRANT BIJ HYPERV
    config.vm.network "private_network", ip: "192.168.56.15"
  
    config.vm.box = "centos/7"
  
    # config.vm.network "public_network"
  
    config.vm.provider "virtualbox" do |v|
        v.name = "CentOSDocker"
        v.memory = 4096
        v.cpus = 2
    end
  
    # configuration for hyperv
    config.vm.provider "hyperv" do |v|
        v.vmname = "DockerForWinVM"
        v.memory = 4096
        v.cpus = 2
    end
   
    config.vm.hostname = "CentOSDocker"
  
    # config.vm.provision :shell, path: "Scripts/prereq.sh"
 
    # config.vm.provision :shell, path: "Scripts/images.sh"
  
    # Verschil in connectiestring = User ID != User
    # config.vm.provision "file", source: "../VoorbeeldProjectLinux", destination: "~/VoorbeeldProject"
    
    # config.vm.provision "file", source: "D:/Documenten/School/HoGent/StageEnBachelorproef/bachelorproef/BachelorproefDocker/09solSportsStore-master", destination: "~/09solSportsStore-master"
  
    config.vm.provision :shell, path: "Scripts/applicaties.sh"   
end

