# -*- mode: ruby -*-

# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'hyperv'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #config.vm.network "private_network", ip: "192.168.1.158"
  
    config.vm.box = "centos/7"
  
    config.vm.network "public_network"
  
    config.vm.provider "hyperv" do |v|
        v.vmname = "CentOSDocker"
        v.memory = 4096
        v.cpus = 2
    end
   
    config.vm.hostname = "CentOSDocker"
  
    config.vm.provision :shell, path: "scripts/prereq.sh"
 
    config.vm.provision :shell, path: "scripts/images.sh"
  
    config.vm.provision "file", source: "D:/Documenten/School/HoGent/StageEnBachelorproef/bachelorproef/BachelorproefDocker/CentOSDocker/VoorbeeldProject", destination: "~/VoorbeeldProject"
  
    config.vm.provision :shell, path: "scripts/applicaties.sh"   
end

