# -*- mode: ruby -*-

# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "mwrock/Windows2016"

  config.vm.network "private_network", ip: "192.168.56.10"
  
  config.vm.provision :shell, path: "scripts/Chocolatey.ps1"
  
  config.vm.provision :shell, path: "scripts/Docker.ps1"
  
end
