# -*- mode: ruby -*-

# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'hyperv'

# require reboot package
# require './vagrant-provision-reboot-plugin'



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # config.vm.network "private_network", ip: "192.168.1.158"

    config.vm.box = "gusztavvargadr/w16s"
    
    config.vm.network "public_network"
    
    config.vm.provider "hyperv" do |v|
        v.vmname = "DockerForWinVM"
        v.memory = 4096
        v.cpus = 2
    end
   
    config.vm.hostname = "DockerForWinVM"
  
    config.vm.provision :shell, path: "provisioning/Chocolatey.ps1"
 
    config.vm.provision :shell, path: "provisioning/OpenSSH.ps1" 

    config.vm.provision :shell, path: "provisioning/Docker-P1.ps1"
    
    config.vm.provision :reload
  
    config.vm.provision :shell, path: "provisioning/Docker-P2.ps1"
  
    config.vm.provision "file", source: "C:/Users/P&G/Documents/BP-SH/DockerForWindows/VoorbeeldProject", destination: "C:/Users/vagrant/VoorbeeldProject"
  
    config.vm.provision :shell, path: "provisioning/images.ps1"
  
    config.vm.provision :shell, path: "provisioning/applicaties.ps1"
  
end
